upd: simplify the console setting init script.

diff --git a/init-scripts/etc/init.d/console b/init-scripts/etc/init.d/console
--- a/init-scripts/etc/init.d/console
+++ b/init-scripts/etc/init.d/console
@@ -1,6 +1,6 @@
 #!/bin/sh
 # console init script for sysvinit
-# apathy 1.2 - mssx86 (mss@waifu.club)
+# apathy 1.3 - mssx86 (mss@waifu.club)
 
 # default-start --> S
 # description ----> set up fonts and lang settings from /etc/sysconfig/console
@@ -14,51 +14,28 @@ FONT="ter-v12n -m 8859-1"
 
 case "${1}" in
  start)
-  
-  # a >> check if the script needs to anything first
-  if [ -z "${KEYMAP}" ]			&&
-     [ -z "${KEYMAP_CORRECTIONS}" ]	&&
-     [ -z "${FONT}" ]			&&
-     [ -z "${LEGACY_CHARSET}" ]		&&
-     [ ! "${UNICODE}" = "1" ]
-  then
-   exit 1
-  fi
 
   log_info_msg "setting up the ${c_lcyan}linux console${c_reset}."
   
-  # b >> check if fb console is used
-  [ -d /sys/class/graphics/fb0 ] && use_fb=1 || use_fb=0
+  # a >> if fb console is used, set font in utf8 for every console
+  if [ -d /sys/class/graphics/fb0 ]; then MODE_COMMAND="${MODE_COMMAND} && setfont ${FONT}"; fi
 
-  # c >> figure out the command to set the console into the desired mode
-  if [ "${UNICODE}" = "1" ]
-   then
-    MODE_COMMAND="printf '\033%G' && kbd_mode -u"		||
-    MODE_COMMAND="printf '\033%@\033(K' && kbd_mode -a"
-  fi
+  # b >> figure out the command to set the console into the desired mode
+  MODE_COMMAND="printf '\033%G' && kbd_mode -u" \
+   || MODE_COMMAND="printf '\033%@\033(K' && kbd_mode -a" \
+   || failed=1
 
-  # d >> set font for each vt
-  [ ! "${use_fb}" = "1" ] || [ -z "${FONT}" ] || MODE_COMMAND="${MODE_COMMAND} && setfont ${FONT}"
+  # c >> apply the mode setting command to all terms in inittab
+  for TTY in $(grep 'respawn' /etc/inittab | awk '{gsub("--noclear",""); gsub("tty",""); print $2}')
+   do
+    openvt -f -w -c ${TTY} -- /bin/sh -c "${MODE_COMMAND}" || failed=1
+   done
 
-  # e >> apply the mode setting command to all terms in inittab
-  for TTY in $(grep '^[^#].*respawn:/sbin/agetty' /etc/inittab | grep -o '\btty[[:digit:]]*\b')
-  do
-   openvt -f -w -c ${TTY#tty} -- /bin/sh -c "${MODE_COMMAND}" || failed=1
-  done
+  # d >> set keymap
+  loadkeys ${KEYMAP} >/dev/null 2>&1 || failed=1; fi
 
-  # f >> set font and keymap if not set above
-  [ "${use_fb}" = "1" ] || [ -z "${FONT}" ] || setfont $FONT || failed=1
-  [ -z "${KEYMAP}" ] || loadkeys ${KEYMAP} >/dev/null 2>&1 || failed=1
-  [ -z "${KEYMAP_CORRECTIONS}" ] || loadkeys ${KEYMAP_CORRECTIONS} >/dev/null 2>&1 || failed=1
-
-  # g >> convert $LEGACY_CHARSET to utf-8
-  [ -z "$LEGACY_CHARSET" ] || dumpkeys -c "$LEGACY_CHARSET" | loadkeys -u >/dev/null 2>&1 || failed=1
-
-  # h >> if anything failed, exit with it
-  (exit $failed)
-  evalret
-
-  exit $failed
+  # e >> if anything failed, exit with it
+  (exit $failed); evalret; exit $failed
  ;;
  *)
   printf "usage: ${0} {start}.\n"
