rewrote: (apathy-utils/) apathy-funcs.

diff --git a/apathy-utils/apathy-funcs b/apathy-utils/apathy-funcs
--- a/apathy-utils/apathy-funcs
+++ b/apathy-utils/apathy-funcs
@@ -3,57 +3,69 @@ umask 022
 export PATH=/usr/sbin:/usr/bin:/sbin:/bin:/mss/bin
 export LANG=C
 
-c_reset="\\033[0;39m"    # grey
-c_green="\\033[1;32m"   # green
-c_red="\\033[1;31m"   # red
-c_lcyan="\\033[1;36m"      # light cyan
-c_blue="\\033[1;34m"   # blue
+# 1 >> define colors
+ c_res="\033[0;39m"
 
-## set cursor position commands
-col="\\033[76G"
-wcol="\\033[70G"
-cur_up="\\033[1A\\033[0G"
-cur_zero="\\033[0G"
+cl_blk="\033[0;30m"
+cl_red="\033[0;31m"
+cl_grn="\033[0;32m"
+cl_yel="\033[0;33m"
+cl_blu="\033[0;34m"
+cl_mgn="\033[0;35m"
+cl_cyn="\033[0;36m"
+cl_whi="\033[0;37m"
 
-# set colors
-sbefore="   "
-succ="${c_green} * ${c_reset}"
-fail="${c_red} ! ${c_reset}"
+cb_blk="\033[1;30m"
+cb_red="\033[1;31m"
+cb_grn="\033[1;32m"
+cb_yel="\033[1;33m"
+cb_blu="\033[1;34m"
+cb_mgn="\033[1;35m"
+cl_grn="\033[1;36m"
+cb_whi="\033[1;37m"
 
-succ_end="${c_green} done${c_reset}"
-fail_end="${c_red} fail${c_reset}"
-memearrow="${c_lcyan} > ${c_reset}"
-askq="${c_blue} ? ${c_reset}"
+# 2 >> define prompts
+    sbefore="   "
+    pbefore=" "
+   cur_zero="\\033[0G"
 
-# printing
-aprint(){       printf "${memearrow}${@}\n"; return 0; }
-aprint_nm(){    printf "${sbefore}${@}\n";   return 0; }
-aprint_ret(){   printf "${sbefore}${@}";     return 0; }
-aprint_ask(){   printf "${askq}${@}";        return 0; }
+    s_fail="${cb_red}f${c_res}"
+    s_warn="${cb_blu}w${c_res}"
+    s_succ="${cb_grn}s${c_res}"
 
-aprint_nc(){    printf "\n"; }
-aprint_succ(){  printf "${sbefore}${@}"; printf "${cur_zero}${succ}${col}${succ_end}\n"; return 0; }
-aprint_fail(){  printf "${sbefore}${@}"; printf "${cur_zero}${fail}${col}${fail_end}\n"; return 0; }
+memearrow="${pbefore}${cl_grn}>${c_res} "
+     askq="${pbefore}${cb_blu}?${c_res} "
 
-aprint_patch(){ printf "${c_lcyan} p ${c_green}${@}${c_reset}."; return 0; }
-aprint_pvars(){ aprint_ret "${c_blue}${1}\t${c_reset}:${c_lcyan} ${2}${c_reset}\n"; return 0; }
+# 3 >> printing functions
+aprint(){       printf "${memearrow}${@}\n"; }
+aprint_nc(){    printf "\n";                 }
+aprint_nm(){    printf "${sbefore}${@}\n";   }
+aprint_ret(){   printf "${sbefore}${@}";     }
+aprint_ask(){   printf "${askq}${@}";        }
 
-aprint_usage(){ aprint "${c_green}usage${c_reset}: ${@}"; }
+failprompt(){   printf "${cur_zero}${pbefore}${s_fail}\n"; }
+warnprompt(){   printf "${cur_zero}${pbefore}${s_warn}\n"; }
+succprompt(){   printf "${cur_zero}${pbefore}${s_succ}\n"; }
 
-lsdetail(){     aprint "${c_green}${1}\t${c_blue}:${c_reset} ${2}";}
+aprint_fail(){  printf "${sbefore}${@}"; failprompt; }
+aprint_warn(){  printf "${sbefore}${@}"; warnprompt; }
+aprint_succ(){  printf "${sbefore}${@}"; succprompt; }
 
-# evaluation
+aprint_patch(){ aprint_ret "${cl_grn}${@}${c_res}";              }
+aprint_usage(){ aprint "${cb_red}usage${cb_blu}:${c_res} ${@}";  }
+lsdetail(){     aprint "${cb_red}${1}\t${cb_blu}:${c_res} ${2}"; }
+
+# 4 >> checks and evaluation functions
 evalret(){
  local error_value="${?}"
- if [ ${error_value} = 0 ]; then aprint_succ; else aprint_fail; fi
+ if [ ${error_value} -eq 0 ]; then succprompt; else failprompt; fi
 }
 
 evalretkill(){
  local error_value="${?}"
-  if [ ${error_value} = 0 ]; then aprint_succ; else aprint_fail; exit 1; fi
+ if [ ${error_value} -eq 0 ]; then succprompt; else failprompt; exit 1; fi
 }
 
-# checks
 rootcheck(){
  if [ "$(id -u)" -ne 0 ]
   then
