upd: update init-scripts with apathy-musl's.

diff --git a/init-scripts/sbin/ifcfg b/init-scripts/sbin/ifcfg
--- a/init-scripts/sbin/ifcfg
+++ b/init-scripts/sbin/ifcfg
@@ -1,33 +1,29 @@
-#!/bin/sh
-# /sbin/ifcfg script for sysvinit
-# apathy 1.2 - mssx86 (mss@waifu.club
+#! /bin/sh
 # SPDX-License-Identifier: GPL-2.0
 
-CheckForwarding(){
- local sbase fwd
- sbase=/proc/sys/net/ipv4/conf
- fwd=0
- if [ -d $sbase ]
-  then
-   for dir in $sbase/*/forwarding
-    do
-     fwd=$(( fwd + $(cat "$dir") ))
+CheckForwarding () {
+  local sbase fwd
+  sbase=/proc/sys/net/ipv4/conf
+  fwd=0
+  if [ -d $sbase ]; then
+    for dir in $sbase/*/forwarding; do
+      fwd=$(( fwd + $(cat "$dir") ))
     done
   else
-  fwd=2
- fi
- return $fwd
+    fwd=2
+  fi
+  return $fwd
 }
 
-RestartRDISC(){
- killall -HUP rdisc || rdisc -fs
+RestartRDISC () {
+  killall -HUP rdisc || rdisc -fs
 }
 
-ABCMaskLen(){
+ABCMaskLen () {
   local class;
 
   class=${1%%.*}
-  if [ "$1" = "" ] || [ $class -eq 0 ] || [ $class -ge 224 ]; then return 0
+  if [ "$1" = "" -o $class -eq 0 -o $class -ge 224 ]; then return 0
   elif [ $class -ge 224 ]; then return 0
   elif [ $class -ge 192 ]; then return 24
   elif [ $class -ge 128 ]; then return 16
@@ -37,9 +33,8 @@ ABCMaskLen(){
 label="label $1"
 ldev="$1"
 dev=${1%:*}
-if [ "$dev" = "" ] || [ "$1" = "help" ]
- then
-  echo "usage: ifcfg DEV [[add|del [ADDR[/LEN]] [PEER] | stop]" 1>&2
+if [ "$dev" = "" -o "$1" = "help" ]; then
+  echo "Usage: ifcfg DEV [[add|del [ADDR[/LEN]] [PEER] | stop]" 1>&2
   echo "       add - add new address" 1>&2
   echo "       del - delete address" 1>&2
   echo "       stop - completely disable IP" 1>&2
@@ -49,100 +44,84 @@ shift
 
 CheckForwarding
 fwd=$?
-if [ $fwd -ne 0 ]
- then
-  printf "forwarding is on or its state is unknown ($fwd). ok, no RDISC." 1>&2
+if [ $fwd -ne 0 ]; then
+  echo "Forwarding is ON or its state is unknown ($fwd). OK, No RDISC." 1>&2
 fi
 
 
 deleting=0
 case "$1" in
- add)
-  shift
- ;;
- stop)
-  if [ "$ldev" != "$dev" ]
-   then
-    printf "cannot stop alias $ldev.\n" 1>&2
-    exit 1
+add) shift ;;
+stop)
+  if [ "$ldev" != "$dev" ]; then
+    echo "Cannot stop alias $ldev" 1>&2
+    exit 1;
   fi
-
   ip -4 addr flush dev $dev $label || exit 1
   if [ $fwd -eq 0 ]; then RestartRDISC; fi
-  exit 0
- ;;
- del*)
-  deleting=1
-  shift
- ;;
- *)
+  exit 0 ;;
+del*)
+  deleting=1; shift ;;
+*)
 esac
 
 ipaddr=
 pfxlen=
-if [ ! "$1" = "" ]
- then
+if [ "$1" != "" ]; then
   ipaddr=${1%/*}
-  
-  if [ ! "$1" = "$ipaddr" ]; then pfxlen=${1#*/}; fi
-  if [ "$ipaddr" = "" ]
-   then
-    printf "$1 is a bad ip address.\n" 1>&2
+  if [ "$1" != "$ipaddr" ]; then
+    pfxlen=${1#*/}
+  fi
+  if [ "$ipaddr" = "" ]; then
+    echo "$1 is bad IP address." 1>&2
     exit 1
   fi
 fi
 shift
 
 peer=$1
-if [ ! "$peer" = "" ]
- then
-  if [ ! "$pfxlen" = "" ] && [ "$pfxlen" = "32" ]
-   then
-    printf "peer address with non-trivial netmask.\n" 1>&2
+if [ "$peer" != "" ]; then
+  if [ "$pfxlen" != "" -a "$pfxlen" != "32" ]; then
+    echo "Peer address with non-trivial netmask." 1>&2
     exit 1
   fi
   pfx="$ipaddr peer $peer"
- else
-  if [ "$ipaddr" = "" ]
-   then
-    printf "missing ip address argument.\n" 1>&2
+else
+  if [ "$ipaddr" = "" ]; then
+    echo "Missing IP address argument." 1>&2
     exit 1
   fi
-  if [ "$pfxlen" = "" ]
-   then
+  if [ "$pfxlen" = "" ]; then
     ABCMaskLen $ipaddr
     pfxlen=$?
   fi
   pfx="$ipaddr/$pfxlen"
 fi
 
-if [ "$ldev" = "$dev" ] && [ ! "$ipaddr" = "" ]; then label=; fi
+if [ "$ldev" = "$dev" -a "$ipaddr" != "" ]; then
+  label=
+fi
 
-if [ $deleting -ne 0 ]
- then
+if [ $deleting -ne 0 ]; then
   ip addr del $pfx dev $dev $label || exit 1
   if [ $fwd -eq 0 ]; then RestartRDISC; fi
   exit 0
 fi
 
 
-if ! ip link set up dev $dev
- then
-  printf "error: cannot enable interface $dev.\n" 1>&2
+if ! ip link set up dev $dev ; then
+  echo "Error: cannot enable interface $dev." 1>&2
   exit 1
 fi
-
 if [ "$ipaddr" = "" ]; then exit 0; fi
 
-if ! arping -q -c 2 -w 3 -D -I $dev $ipaddr
- then
-  printf "error: some host already uses address $ipaddr on $dev.\n" 1>&2
+if ! arping -q -c 2 -w 3 -D -I $dev $ipaddr ; then
+  echo "Error: some host already uses address $ipaddr on $dev." 1>&2
   exit 1
 fi
 
-if ! ip address add $pfx brd + dev $dev $label
- then
-  printf "error: failed to add $pfx on $dev.\n" 1>&2
+if ! ip address add $pfx brd + dev $dev $label; then
+  echo "Error: failed to add $pfx on $dev." 1>&2
   exit 1
 fi
 
@@ -153,19 +132,15 @@ noarp=$?
 
 ip route add unreachable 224.0.0.0/24 >/dev/null 2>&1
 ip route add unreachable 255.255.255.255 >/dev/null 2>&1
-
-if [ "`ip link ls $dev | grep -c MULTICAST`" -ge 1 ]
- then
+if [ "`ip link ls $dev | grep -c MULTICAST`" -ge 1 ]; then
   ip route add 224.0.0.0/4 dev $dev scope global >/dev/null 2>&1
 fi
 
-if [ $fwd -eq 0 ]
- then
-  if [ $noarp -eq 0 ]; then ip ro append default dev $dev metric 30000 scope global
-  elif [ "$peer" != "" ]
-   then
-    if ping -q -c 2 -w 4 $peer
-     then
+if [ $fwd -eq 0 ]; then
+  if [ $noarp -eq 0 ]; then
+    ip ro append default dev $dev metric 30000 scope global
+  elif [ "$peer" != "" ]; then
+    if ping -q -c 2 -w 4 $peer ; then
       ip ro append default via $peer dev $dev metric 30001
     fi
   fi
